name: Build and Push (Hathora via Depot)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # paths:
    #   - 'Dockerfile'
    #   - '.github/workflows/hathora-build-push.yml'
    #   - '.hathora_build/**'
    #   - 'python/**'

jobs:
  build:
    runs-on: ubuntu-latest
    # Permissions to use OIDC token authentication
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Depot
        uses: depot/setup-action@v1

      - name: Build and Push with Depot
        uses: depot/build-push-action@v1
        with:
          project: pxptmtxcxf
          context: .
          save: true
          save-tag: "hathora-${{ github.sha }}"